import Head from "next/head";
import { Input, Stack } from "@chakra-ui/react";
import Image from "next/image";
import imageNakajima from "./IMG_8366.jpeg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header>
          <h1>日程調整アプリ</h1>
        </header>
        <p>グループ名</p>
        <Stack spacing={3}>
          <Input placeholder="medium size" size="md" />
        </Stack>
        <div style={{ position: "relative", width: "100px", height: "100px" }}>
          <Image src={imageNakajima} alt="身長が高すぎた中島" />
        </div>

        <footer>
          <p>Styles作成</p>
        </footer>
      </main>
    </>
  );
}
